package jdbc;

// Generated 4 mars 2014 14:38:22 by Hibernate Tools 4.0.0

/**
 * Contexte generated by hbm2java
 */
public class Contexte implements java.io.Serializable {

	private Integer idContexte;
	private String nom;
	private String couleur;
	private int fkIdUtilisateur;

	public Contexte() {
	}

	public Contexte(String nom, String couleur, int fkIdUtilisateur) {
		this.nom = nom;
		this.couleur = couleur;
		this.fkIdUtilisateur = fkIdUtilisateur;
	}

	public Integer getIdContexte() {
		return this.idContexte;
	}

	public void setIdContexte(Integer idContexte) {
		this.idContexte = idContexte;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getCouleur() {
		return this.couleur;
	}

	public void setCouleur(String couleur) {
		this.couleur = couleur;
	}

	public int getFkIdUtilisateur() {
		return this.fkIdUtilisateur;
	}

	public void setFkIdUtilisateur(int fkIdUtilisateur) {
		this.fkIdUtilisateur = fkIdUtilisateur;
	}

}
