package jdbc;

// Generated 4 mars 2014 12:49:37 by Hibernate Tools 4.0.0

/**
 * Synchro generated by hbm2java
 */
public class Synchro implements java.io.Serializable {

	private SynchroId id;

	public Synchro() {
	}

	public Synchro(SynchroId id) {
		this.id = id;
	}

	public SynchroId getId() {
		return this.id;
	}

	public void setId(SynchroId id) {
		this.id = id;
	}

}
