package jdbc;

// Generated 20 févr. 2014 15:04:44 by Hibernate Tools 4.0.0

/**
 * Synchro generated by hbm2java
 */
public class Synchro implements java.io.Serializable {

	private String fkIdEvent;
	private int fkIdTodo;
	private int idCalendar;

	public Synchro() {
	}

	public Synchro(String fkIdEvent, int fkIdTodo, int idCalendar) {
		this.fkIdEvent = fkIdEvent;
		this.fkIdTodo = fkIdTodo;
		this.idCalendar = idCalendar;
	}

	public String getFkIdEvent() {
		return this.fkIdEvent;
	}

	public void setFkIdEvent(String fkIdEvent) {
		this.fkIdEvent = fkIdEvent;
	}

	public int getFkIdTodo() {
		return this.fkIdTodo;
	}

	public void setFkIdTodo(int fkIdTodo) {
		this.fkIdTodo = fkIdTodo;
	}

	public int getIdCalendar() {
		return this.idCalendar;
	}

	public void setIdCalendar(int idCalendar) {
		this.idCalendar = idCalendar;
	}

}
