package jdbc;

// Generated 21 févr. 2014 11:09:09 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TodoTest generated by hbm2java
 */
public class TodoTest implements java.io.Serializable {

	private Integer idTodo;
	private String titre;
	private String description;
	private int degreImportance;
	private String contexte;
	private Date echeanceBegin;
	private Date echeanceEnd;
	private int fkIdUtilisateur;

	public TodoTest() {
	}

	public TodoTest(String titre, String description, int degreImportance,
			String contexte, Date echeanceBegin, Date echeanceEnd,
			int fkIdUtilisateur) {
		this.titre = titre;
		this.description = description;
		this.degreImportance = degreImportance;
		this.contexte = contexte;
		this.echeanceBegin = echeanceBegin;
		this.echeanceEnd = echeanceEnd;
		this.fkIdUtilisateur = fkIdUtilisateur;
	}

	public Integer getIdTodo() {
		return this.idTodo;
	}

	public void setIdTodo(Integer idTodo) {
		this.idTodo = idTodo;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getDegreImportance() {
		return this.degreImportance;
	}

	public void setDegreImportance(int degreImportance) {
		this.degreImportance = degreImportance;
	}

	public String getContexte() {
		return this.contexte;
	}

	public void setContexte(String contexte) {
		this.contexte = contexte;
	}

	public Date getEcheanceBegin() {
		return this.echeanceBegin;
	}

	public void setEcheanceBegin(Date echeanceBegin) {
		this.echeanceBegin = echeanceBegin;
	}

	public Date getEcheanceEnd() {
		return this.echeanceEnd;
	}

	public void setEcheanceEnd(Date echeanceEnd) {
		this.echeanceEnd = echeanceEnd;
	}

	public int getFkIdUtilisateur() {
		return this.fkIdUtilisateur;
	}

	public void setFkIdUtilisateur(int fkIdUtilisateur) {
		this.fkIdUtilisateur = fkIdUtilisateur;
	}

}
